### PR TITLE
Fix prompt to leave when downloading attachments

### LINKED ISSUE #556: Prompted to leave page when opening attachment
**Given** I am reading a mail with attachments and I have a composer openened (also minimize) with new content written in it.
**When** I click on an attachment
**What happens** I am prompted asking if I want to leave the page with unsaved data
**What should happen** I should not be prompted because I am not leaving the page

The solution is to add a `download` attribute on the anchor tag, to tell the browser I am downloading a file and not leaving the page. (see https://developer.mozilla.org/en-US/docs/Web/HTML/Element/a)
The file to modify is `attachment-download-action.pug`.

### PR DESCRIPTION
**Pull request by alagane**
Close #556

### CODE REVIEW

**Review by fabienmoyon — DISMISSED** [review]
:man_shrugging:

**Comment by alagane** [comment]
Force-pushed to adapt tests (only tests changed)

**Comment by fabienmoyon** [comment]
@alagane /var/jenkins_home/workspace/esn-frontend-inbox_PR-558/src/linagora.esn.unifiedinbox/app/controllers.spec.js

  11:53  error  'navigateTo' is assigned a value but never used  no-unused-vars



✖ 1 problem (1 error, 0 warnings)

**Comment by alagane** [comment]
Force-pushed to remove unused variable on tests (I forgot to run npm run lint)

**Review by fabienmoyon — APPROVED** [review]

**Review by rezk2ll — APPROVED** [review]

**Pull request merged**
