### PR TITLE
#482 Fix token Api error

### PR DESCRIPTION
**Pull request by oubchid**

### CODE REVIEW

**Review by chibenwa — COMMENTED** [review]
Do we have a unit test?

**Comment by oubchid** [comment]
> Do we have a unit test?

yes  #479

**Comment by chibenwa** [comment]
Why not have had put the two in the same PR, I do not understand...

**Comment by oubchid** [comment]
> Why not have had put the two in the same PR, I do not understand...

As you can see it's a fix of the pervoius PR already **merged**

**Comment by chibenwa** [comment]
Sorry it is not clear.

It broke a build? If so we should say it.

If not we were missing a test and we should add it.

Also we should have a link to the problematic pr and an explanation of the defect.

**Comment by oubchid** [comment]
It's the next part to fix this issue https://github.com/linagora/esn-frontend-inbox/issues/453
and the PR is
https://github.com/linagora/esn-frontend-inbox/pull/479/

**Review by alagane — APPROVED** [review]

**Comment by rezk2ll** [comment]
we still experience the issue?

**Comment by oubchid** [comment]
Error fixed here https://github.com/linagora/esn-frontend-common-libs/pull/225

**Pull request closed without merging**
