### PR TITLE
Revert "removed unused linagora.esn.james module from inbox"

### PR DESCRIPTION
**Pull request by rezk2ll**
Reverts linagora/esn-frontend-inbox#455

it seems the admin SPA can't build without it. so we might need to copy the james stuff in the admin SPA first.

or move it here https://github.com/linagora/esn-frontend-inbox-james

### CODE REVIEW

**Review by fabienmoyon — APPROVED** [review]

**Comment by tanandy** [comment]
can you fix admin spa ? we dont need to revert then if it works in inbox

**Comment by fabienmoyon** [comment]
we revert it and we will move what we don't need in to the inbox-james for the admin SPA

**Comment by tanandy** [comment]
but this is not the spa admin. Do we need to keep james stuff inside inbox ?

**Comment by rezk2ll** [comment]
@atan-linagora for now let's revert it.
i copied both, `esn-frontend-inbox-james` and `linagora.esn.james` in admin and integrated them but the admin SPA still requires stuff from inbox `esn.inbox.libs` without requiring it in the package.json ( it relies on `esn-frontend-inbox-james` to install it which is bad )
so I suggest we just merge this revert PR and fix the admin potential problems and worry about the mess we have with dependencies later.

**Review by tanandy — APPROVED** [review]
ok

**Pull request merged**
